export const ArticlesSlugsArray = [
  {
    params: {
      slug: 'un-week-end-en-alsace-au-coeur-de-la-magie-de-noel',
    },
  },
  {
    params: {
      slug: 'les-jeux-de-pistes-urbains-une-aventure-trepidante-pour-un-city-trip-reussi',
    },
  },
  {
    params: {
      slug: 'voyages-et-pourboires-ce-quil-faut-savoir',
    },
  },
  {
    params: {
      slug: 'quelle-destination-pour-un-voyage-de-noces-2',
    },
  },
  {
    params: {
      slug: 'que-faire-a-new-york-10-idees-originales-sortir-des-sentiers-battus',
    },
  },
  {
    params: {
      slug: 'activites-improbables-a-faire-en-voyage',
    },
  },
  {
    params: {
      slug: 'briefing-pour-voyager-moins-cher',
    },
  },
  {
    params: {
      slug: 'top-des-destinations-encore-hors-des-sentiers-battus',
    },
  },
  {
    params: {
      slug: 'le-petit-guide-pour-bien-preparer-sa-valise',
    },
  },
  {
    params: {
      slug: 'guide-demarrage-explomaker',
    },
  },
  {
    params: {
      slug: 'fonctionnement-explomaker',
    },
  },
]

export const spotsSlugsArray = [
  { params: { slug: 'fatu-hiva' } },
  { params: { slug: 'ua-pou' } },
  { params: { slug: 'marquises' } },
  { params: { slug: 'tahuata' } },
  { params: { slug: 'hiva-oa' } },
  { params: { slug: 'tahaa' } },
  { params: { slug: 'mataiva' } },
  { params: { slug: 'raiatea' } },
  { params: { slug: 'huahine' } },
  { params: { slug: 'biarritz' } },
  { params: { slug: 'la-rochelle' } },
  { params: { slug: 'fakarava' } },
  { params: { slug: 'la-havane' } },
  { params: { slug: 'clermont-ferrand' } },
  { params: { slug: 'bergerac' } },
  { params: { slug: 'salon-de-provence' } },
  { params: { slug: 'aurillac' } },
  { params: { slug: 'gap' } },
  { params: { slug: 'rocherfort' } },
  { params: { slug: 'saint-nazaire' } },
  { params: { slug: 'poitiers' } },
  { params: { slug: 'pau' } },
  { params: { slug: 'tours' } },
  { params: { slug: 'rennes' } },
  { params: { slug: 'vannes' } },
  { params: { slug: 'quimper' } },
  { params: { slug: 'bretignolles-sur-mer' } },
  { params: { slug: 'biscarosse' } },
  { params: { slug: 'bayonne' } },
  { params: { slug: 'le-croisic' } },
  { params: { slug: 'lile-de-groix' } },
  { params: { slug: 'hyeres' } },
  { params: { slug: 'royan' } },
  { params: { slug: 'concarneau' } },
  { params: { slug: 'sologne' } },
  { params: { slug: 'doha' } },
  { params: { slug: 'culross' } },
  { params: { slug: 'islay' } },
  { params: { slug: 'tobermory' } },
  { params: { slug: 'portree' } },
  { params: { slug: 'highlands' } },
  { params: { slug: 'edinbourg' } },
  { params: { slug: 'glasgow' } },
  { params: { slug: 'eilat' } },
  { params: { slug: 'masada' } },
  { params: { slug: 'navigli' } },
  { params: { slug: 'rovinj' } },
  { params: { slug: 'zadar' } },
  { params: { slug: 'dubrovnik' } },
  { params: { slug: 'ecosse' } },
  { params: { slug: 'ostende' } },
  { params: { slug: 'mons' } },
  { params: { slug: 'anvers' } },
  { params: { slug: 'bruges' } },
  { params: { slug: 'valence-2' } },
  { params: { slug: 'grenade-2' } },
  { params: { slug: 'saint-barthelemy' } },
  { params: { slug: 'zimbabwe-3' } },
  { params: { slug: 'belize-2' } },
  { params: { slug: 'lituanie' } },
  { params: { slug: 'rwanda-2' } },
  { params: { slug: 'tanzanie' } },
  { params: { slug: 'kenya' } },
  { params: { slug: 'serbie' } },
  { params: { slug: 'paraguay-2' } },
  { params: { slug: 'salvador-2' } },
  { params: { slug: 'mozambique-2' } },
  { params: { slug: 'lettonie' } },
  { params: { slug: 'ouzbekistan' } },
  { params: { slug: 'qatar-2' } },
  { params: { slug: 'algerie' } },
  { params: { slug: 'andorre' } },
  { params: { slug: 'vatican' } },
  { params: { slug: 'slovenie' } },
  { params: { slug: 'uruguay-2' } },
  { params: { slug: 'chypre' } },
  { params: { slug: 'colombie' } },
  { params: { slug: 'israel-2' } },
  { params: { slug: 'bresil' } },
  { params: { slug: 'suede' } },
  { params: { slug: 'tunisie' } },
  { params: { slug: 'philippines-2' } },
  { params: { slug: 'tchequie' } },
  { params: { slug: 'danemark' } },
  { params: { slug: 'suisse' } },
  { params: { slug: 'viet-nam' } },
  { params: { slug: 'croatie' } },
  { params: { slug: 'indonesie' } },
  { params: { slug: 'pologne' } },
  { params: { slug: 'stockholm' } },
  { params: { slug: 'tel-aviv' } },
  { params: { slug: 'varsovie' } },
  { params: { slug: 'san-francisco' } },
  { params: { slug: 'jerusalem' } },
  { params: { slug: 'bruxelles' } },
  { params: { slug: 'florence' } },
  { params: { slug: 'venise' } },
  { params: { slug: 'milan' } },
  { params: { slug: 'los-angeles' } },
  { params: { slug: 'singapour' } },
  { params: { slug: 'macao-2' } },
  { params: { slug: 'iles-eoliennes' } },
  { params: { slug: 'madere' } },
  { params: { slug: 'sardaigne' } },
  { params: { slug: 'zanzibar' } },
  { params: { slug: 'guatemala-2' } },
  { params: { slug: 'hongrie' } },
  { params: { slug: 'afrique-du-sud' } },
  { params: { slug: 'roumanie' } },
  { params: { slug: 'costa-rica-2' } },
  { params: { slug: 'bulgarie' } },
  { params: { slug: 'malaisie' } },
  { params: { slug: 'emirats-arabes-unis' } },
  { params: { slug: 'tikehau' } },
  { params: { slug: 'rangiroa' } },
  { params: { slug: 'maupiti' } },
  { params: { slug: 'maldives-2' } },
  { params: { slug: 'bilbao' } },
  { params: { slug: 'estonie' } },
  { params: { slug: 'sarlat' } },
  { params: { slug: 'islande' } },
  { params: { slug: 'togo-2' } },
  { params: { slug: 'burkina-faso-2' } },
  { params: { slug: 'senegal-2' } },
  { params: { slug: 'egypte' } },
  { params: { slug: 'dijon' } },
  { params: { slug: 'arles' } },
  { params: { slug: 'avignon' } },
  { params: { slug: 'cannes' } },
  { params: { slug: 'charleville-mezieres' } },
  { params: { slug: 'metz' } },
  { params: { slug: 'nancy' } },
  { params: { slug: 'reims' } },
  { params: { slug: 'strasbourg' } },
  { params: { slug: 'aix-en-provence' } },
  { params: { slug: 'nantes' } },
  { params: { slug: 'le-mans' } },
  { params: { slug: 'la-roche-sur-yon' } },
  { params: { slug: 'ile-de-noirmoutier' } },
  { params: { slug: 'toulouse' } },
  { params: { slug: 'perpignan' } },
  { params: { slug: 'nimes' } },
  { params: { slug: 'narbonne' } },
  { params: { slug: 'montpellier' } },
  { params: { slug: 'montauban' } },
  { params: { slug: 'carcassonne' } },
  { params: { slug: 'beziers' } },
  { params: { slug: 'dunkerque' } },
  { params: { slug: 'amiens' } },
  { params: { slug: 'ajaccio' } },
  { params: { slug: 'brest' } },
  { params: { slug: 'rouen' } },
  { params: { slug: 'mont-saint-michel' } },
  { params: { slug: 'giverny' } },
  { params: { slug: 'caen' } },
  { params: { slug: 'colmar' } },
  { params: { slug: 'amboise' } },
  { params: { slug: 'orleans' } },
  { params: { slug: 'bourges' } },
  { params: { slug: 'etats-unis' } },
  { params: { slug: 'portugal-2' } },
  { params: { slug: 'albanie' } },
  { params: { slug: 'vienne' } },
  { params: { slug: 'saint-petersbourg' } },
  { params: { slug: 'russie' } },
  { params: { slug: 'marseille' } },
  { params: { slug: 'bordeaux' } },
  { params: { slug: 'paris' } },
  { params: { slug: 'lyon' } },
  { params: { slug: 'madrid' } },
  { params: { slug: 'bali' } },
  { params: { slug: 'namibie' } },
  { params: { slug: 'lille' } },
  { params: { slug: 'vancouver' } },
  { params: { slug: 'new-york' } },
  { params: { slug: 'prague' } },
  { params: { slug: 'budapest' } },
  { params: { slug: 'barcelone' } },
  { params: { slug: 'oman' } },
  { params: { slug: 'nouvelle-zelande' } },
  { params: { slug: 'tahiti' } },
  { params: { slug: 'moorea' } },
  { params: { slug: 'bora-bora' } },
  { params: { slug: 'pouilles' } },
  { params: { slug: 'polynesie-francaise' } },
  { params: { slug: 'maroc' } },
  { params: { slug: 'autriche' } },
  { params: { slug: 'turquie' } },
  { params: { slug: 'thailande' } },
  { params: { slug: 'royaume-uni' } },
  { params: { slug: 'pays-bas' } },
  { params: { slug: 'monaco' } },
  { params: { slug: 'belgique' } },
  { params: { slug: 'allemagne' } },
  { params: { slug: 'italie-2' } },
  { params: { slug: 'santorin' } },
  { params: { slug: 'grece' } },
  { params: { slug: 'perou' } },
  { params: { slug: 'corse' } },
  { params: { slug: 'cuba' } },
  { params: { slug: 'france' } },
  { params: { slug: 'espagne' } },
  { params: { slug: 'norvege' } },
]
